import Foundation

/// The people who told us something, and what they are owed for it.
///
/// Generated by `Scripts/feedback-sync.sh` at release time from the issues —
/// the app asks no server for anything, so a wall that needed a network call
/// would be a wall that is usually empty. Do not edit by hand.
///
/// This is the whole of the reward, and it is the right one: somebody who
/// reported a bug opens About and finds their own name inside the app they
/// use. No points, no badges, nothing to redeem.
public struct Contributor: Sendable, Hashable, Identifiable {
    public let name: String
    public let reports: Int
    public var id: String { name }
}

public enum Contributors {
    public static let all: [Contributor] = [
        Contributor(name: "익명", reports: 1),
    ]

    public static var total: Int { all.reduce(0) { $0 + $1.reports } }
}
