/**
 * The LaTeX spellings of characters a `.bib` file cannot hold plainly.
 *
 * GENERATED — do not edit. Run `node tools/generate-latex-table.mjs` to
 * rebuild it from `Packages/PaperTimeKit/Sources/Bibliography/LaTeXEscaping.swift`,
 * which is the source of truth for both builds. Transcribing it by hand would
 * mean a name like "Almudévar" could come out one way on a Mac and another on
 * Windows, from the same library.
 *
 * Built from: specialCharacters (10), accentedLetters (181), punctuation (14).
 */
export const LATEX_ESCAPES: Record<string, string> = {
  "\\": "\\textbackslash{}",
  "&": "\\&",
  "%": "\\%",
  "$": "\\$",
  "#": "\\#",
  "_": "\\_",
  "{": "\\{",
  "}": "\\}",
  "~": "\\textasciitilde{}",
  "^": "\\textasciicircum{}",
  "À": "{\\`A}",
  "Á": "{\\'A}",
  "Â": "{\\^A}",
  "Ã": "{\\~A}",
  "Ä": "{\\\"A}",
  "Å": "{\\AA}",
  "Æ": "{\\AE}",
  "Ç": "{\\c C}",
  "È": "{\\`E}",
  "É": "{\\'E}",
  "Ê": "{\\^E}",
  "Ë": "{\\\"E}",
  "Ì": "{\\`I}",
  "Í": "{\\'I}",
  "Î": "{\\^I}",
  "Ï": "{\\\"I}",
  "Ð": "{\\DH}",
  "Ñ": "{\\~N}",
  "Ò": "{\\`O}",
  "Ó": "{\\'O}",
  "Ô": "{\\^O}",
  "Õ": "{\\~O}",
  "Ö": "{\\\"O}",
  "Ø": "{\\O}",
  "Ù": "{\\`U}",
  "Ú": "{\\'U}",
  "Û": "{\\^U}",
  "Ü": "{\\\"U}",
  "Ý": "{\\'Y}",
  "Þ": "{\\TH}",
  "ß": "{\\ss}",
  "à": "{\\`a}",
  "á": "{\\'a}",
  "â": "{\\^a}",
  "ã": "{\\~a}",
  "ä": "{\\\"a}",
  "å": "{\\aa}",
  "æ": "{\\ae}",
  "ç": "{\\c c}",
  "è": "{\\`e}",
  "é": "{\\'e}",
  "ê": "{\\^e}",
  "ë": "{\\\"e}",
  "ì": "{\\`i}",
  "í": "{\\'i}",
  "î": "{\\^i}",
  "ï": "{\\\"i}",
  "ð": "{\\dh}",
  "ñ": "{\\~n}",
  "ò": "{\\`o}",
  "ó": "{\\'o}",
  "ô": "{\\^o}",
  "õ": "{\\~o}",
  "ö": "{\\\"o}",
  "ø": "{\\o}",
  "ù": "{\\`u}",
  "ú": "{\\'u}",
  "û": "{\\^u}",
  "ü": "{\\\"u}",
  "ý": "{\\'y}",
  "þ": "{\\th}",
  "ÿ": "{\\\"y}",
  "Ā": "{\\=A}",
  "ā": "{\\=a}",
  "Ă": "{\\u A}",
  "ă": "{\\u a}",
  "Ą": "{\\k A}",
  "ą": "{\\k a}",
  "Ć": "{\\'C}",
  "ć": "{\\'c}",
  "Ĉ": "{\\^C}",
  "ĉ": "{\\^c}",
  "Ċ": "{\\.C}",
  "ċ": "{\\.c}",
  "Č": "{\\v C}",
  "č": "{\\v c}",
  "Ď": "{\\v D}",
  "ď": "{\\v d}",
  "Đ": "{\\DJ}",
  "đ": "{\\dj}",
  "Ē": "{\\=E}",
  "ē": "{\\=e}",
  "Ĕ": "{\\u E}",
  "ĕ": "{\\u e}",
  "Ė": "{\\.E}",
  "ė": "{\\.e}",
  "Ę": "{\\k E}",
  "ę": "{\\k e}",
  "Ě": "{\\v E}",
  "ě": "{\\v e}",
  "Ĝ": "{\\^G}",
  "ĝ": "{\\^g}",
  "Ğ": "{\\u G}",
  "ğ": "{\\u g}",
  "Ġ": "{\\.G}",
  "ġ": "{\\.g}",
  "Ģ": "{\\c G}",
  "ģ": "{\\c g}",
  "Ĥ": "{\\^H}",
  "ĥ": "{\\^h}",
  "Ĩ": "{\\~I}",
  "ĩ": "{\\~i}",
  "Ī": "{\\=I}",
  "ī": "{\\=i}",
  "Ĭ": "{\\u I}",
  "ĭ": "{\\u i}",
  "Į": "{\\k I}",
  "į": "{\\k i}",
  "İ": "{\\.I}",
  "ı": "{\\i}",
  "Ĵ": "{\\^J}",
  "ĵ": "{\\^j}",
  "Ķ": "{\\c K}",
  "ķ": "{\\c k}",
  "Ĺ": "{\\'L}",
  "ĺ": "{\\'l}",
  "Ļ": "{\\c L}",
  "ļ": "{\\c l}",
  "Ľ": "{\\v L}",
  "ľ": "{\\v l}",
  "Ł": "{\\L}",
  "ł": "{\\l}",
  "Ń": "{\\'N}",
  "ń": "{\\'n}",
  "Ņ": "{\\c N}",
  "ņ": "{\\c n}",
  "Ň": "{\\v N}",
  "ň": "{\\v n}",
  "Ō": "{\\=O}",
  "ō": "{\\=o}",
  "Ŏ": "{\\u O}",
  "ŏ": "{\\u o}",
  "Ő": "{\\H O}",
  "ő": "{\\H o}",
  "Œ": "{\\OE}",
  "œ": "{\\oe}",
  "Ŕ": "{\\'R}",
  "ŕ": "{\\'r}",
  "Ŗ": "{\\c R}",
  "ŗ": "{\\c r}",
  "Ř": "{\\v R}",
  "ř": "{\\v r}",
  "Ś": "{\\'S}",
  "ś": "{\\'s}",
  "Ŝ": "{\\^S}",
  "ŝ": "{\\^s}",
  "Ş": "{\\c S}",
  "ş": "{\\c s}",
  "Š": "{\\v S}",
  "š": "{\\v s}",
  "Ţ": "{\\c T}",
  "ţ": "{\\c t}",
  "Ť": "{\\v T}",
  "ť": "{\\v t}",
  "Ũ": "{\\~U}",
  "ũ": "{\\~u}",
  "Ū": "{\\=U}",
  "ū": "{\\=u}",
  "Ŭ": "{\\u U}",
  "ŭ": "{\\u u}",
  "Ů": "{\\r U}",
  "ů": "{\\r u}",
  "Ű": "{\\H U}",
  "ű": "{\\H u}",
  "Ų": "{\\k U}",
  "ų": "{\\k u}",
  "Ŵ": "{\\^W}",
  "ŵ": "{\\^w}",
  "Ŷ": "{\\^Y}",
  "ŷ": "{\\^y}",
  "Ÿ": "{\\\"Y}",
  "Ź": "{\\'Z}",
  "ź": "{\\'z}",
  "Ż": "{\\.Z}",
  "ż": "{\\.z}",
  "Ž": "{\\v Z}",
  "ž": "{\\v z}",
  "Ǎ": "{\\v A}",
  "ǎ": "{\\v a}",
  "Ạ": "{\\d A}",
  "ạ": "{\\d a}",
  "–": "--",
  "—": "---",
  "‘": "`",
  "’": "'",
  "“": "``",
  "”": "''",
  "…": "\\ldots{}",
  " ": "~",
  "°": "{\\textdegree}",
  "×": "{\\texttimes}",
  "±": "{\\textpm}",
  "µ": "{\\textmu}",
  "©": "{\\textcopyright}",
  "→": "{\\textrightarrow}",
  "α": "$\\alpha$",
  "β": "$\\beta$",
  "γ": "$\\gamma$",
  "δ": "$\\delta$",
  "ε": "$\\epsilon$",
  "ζ": "$\\zeta$",
  "η": "$\\eta$",
  "θ": "$\\theta$",
  "ι": "$\\iota$",
  "κ": "$\\kappa$",
  "λ": "$\\lambda$",
  "μ": "$\\mu$",
  "ν": "$\\nu$",
  "ξ": "$\\xi$",
  "π": "$\\pi$",
  "ρ": "$\\rho$",
  "σ": "$\\sigma$",
  "τ": "$\\tau$",
  "υ": "$\\upsilon$",
  "φ": "$\\phi$",
  "χ": "$\\chi$",
  "ψ": "$\\psi$",
  "ω": "$\\omega$",
  "Γ": "$\\Gamma$",
  "Δ": "$\\Delta$",
  "Θ": "$\\Theta$",
  "Λ": "$\\Lambda$",
  "Ξ": "$\\Xi$",
  "Π": "$\\Pi$",
  "Σ": "$\\Sigma$",
  "Φ": "$\\Phi$",
  "Ψ": "$\\Psi$",
  "Ω": "$\\Omega$",
}

/**
 * A field value as BibTeX wants it.
 *
 * Walks the text once and only ever reads from the input, never from what it
 * has already written, so a backslash introduced by the table — the one in
 * `\\textbackslash{}` — can never be picked up and escaped a second time.
 */
export function escapeLaTeX(text: string): string {
  let result = ''
  for (const character of text) {
    result += LATEX_ESCAPES[character] ?? character
  }
  return result
}
