/**
 * Text as search sees it — the port of `PaperTextIndex.fold` and of
 * `TextNormalization.foldedTitle`.
 *
 * One case, no accents, one width; no line breaks, and no hyphen where a word
 * was broken across two lines. That last one is why the fold exists at all: a
 * paper sets "un-\nlearning" at the end of a line, and a reader looking for
 * "unlearning" does not care.
 *
 * Both desktops search the same library, so this has to fold the way the Mac
 * does and not merely in the same spirit. JavaScript has nothing like
 * Foundation's fold — NFKD and `toLowerCase` disagree with it in hundreds of
 * places — so the per-scalar answers are Foundation's own (`foldTable.ts`,
 * generated by asking it), and what happens to the marks after a letter is
 * the rule Foundation was measured to follow (see `foldCluster`). `npm test`
 * holds this to strings folded by the real Swift code.
 */
import { COMBINING, FULL, STRIP_ALL, STRIP_FEW, TITLE_DELTA } from './foldTable.js'

type Table = Map<number, string>

function unpack(packed: string, into: Table = new Map()): Table {
  if (!packed) return into
  for (const entry of packed.split(',')) {
    const [from, to] = entry.split('=')
    into.set(parseInt(from, 16), String.fromCodePoint(...to.split('.').map((part) => parseInt(part, 16))))
  }
  return into
}

function ranges(packed: string): Uint32Array {
  return Uint32Array.from(packed.split(',').filter(Boolean).map((part) => parseInt(part, 16)))
}

function inRanges(list: Uint32Array, value: number): boolean {
  // Pairs of [low, high], sorted: a binary search over the lows.
  let lo = 0
  let hi = list.length / 2 - 1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    if (value < list[mid * 2]) hi = mid - 1
    else if (value > list[mid * 2 + 1]) lo = mid + 1
    else return true
  }
  return false
}

/**
 * Which fold a folded text was made with: the tables' own checksum, and the
 * rules' version after it. Text folded once and kept — the index keeps it —
 * is only good while both are the same; bump the last number whenever the
 * rules below change what they write.
 */
let version: string | null = null

export function foldVersion(): string {
  if (version) return version
  let hash = 0x811c9dc5
  for (const part of [FULL, TITLE_DELTA, STRIP_ALL, STRIP_FEW, COMBINING]) {
    for (let index = 0; index < part.length; index += 1) {
      hash ^= part.charCodeAt(index)
      hash = Math.imul(hash, 0x01000193) >>> 0
    }
  }
  version = `${hash.toString(16)}.1`
  return version
}

interface Tables {
  full: Table
  title: Table
  stripAll: Uint32Array
  stripFew: Uint32Array
  combining: Map<number, number>
  /** Both folds of the first 0x300 code units, where nearly every character
   *  of an English paper lives, as plain arrays. */
  fast: string[]
  fastTitle: string[]
}

/** Unpacked on first use: the window that never searches never pays for it. */
let unpacked: Tables | null = null

function tables(): Tables {
  if (unpacked) return unpacked
  const full = unpack(FULL)
  const title = unpack(TITLE_DELTA, new Map(full))
  for (const [from, to] of [...title]) {
    if (to === String.fromCodePoint(from)) title.delete(from)
  }
  const combining = new Map<number, number>()
  for (const entry of COMBINING.split(',')) {
    const [from, value] = entry.split('=')
    combining.set(parseInt(from, 16), parseInt(value, 16))
  }
  const fast: string[] = []
  const fastTitle: string[] = []
  for (let unit = 0; unit < 0x300; unit += 1) {
    fast.push(full.get(unit) ?? String.fromCharCode(unit))
    fastTitle.push(title.get(unit) ?? String.fromCharCode(unit))
  }
  unpacked = { full, title, stripAll: ranges(STRIP_ALL), stripFew: ranges(STRIP_FEW), combining, fast, fastTitle }
  return unpacked
}

// MARK: - Foundation's clusters

/** A Hangul jamo that joins the one before it into a syllable. */
function isVowelOrTrailingJamo(unit: number): boolean {
  return (unit >= 0x1160 && unit <= 0x11ff) || (unit >= 0xd7b0 && unit <= 0xd7ff)
}

function isHangul(scalar: number): boolean {
  return (scalar >= 0x1100 && scalar <= 0x11ff) || (scalar >= 0xa960 && scalar <= 0xa97f)
    || (scalar >= 0xac00 && scalar <= 0xd7ff)
}

/** A mark that takes no room of its own: nonspacing or enclosing. */
const NONSPACING = /^[\p{Mn}\p{Me}]$/u

/**
 * Whether a scalar belongs to the letter before it, as Foundation sees it.
 *
 * Not the grapheme rules. Foundation's fold groups a letter with the marks
 * after it whatever comes before — a mark after a line break goes with the
 * line break, and is dropped with it — which is where `foldedTitle`, folding a
 * whole string at once, parts from the text fold, which folds a grapheme at a
 * time. A spacing mark it does not know (an Indic vowel sign) stands as a
 * letter of its own, and so does the joiner U+200D: the marks after them go
 * by their rule.
 */
function joinsPrevious(scalar: number, all: Uint32Array): boolean {
  if (scalar < 0x300 || scalar === 0x200d) return false
  if (inRanges(all, scalar)) return true
  return NONSPACING.test(String.fromCodePoint(scalar))
}

/**
 * A letter and the marks after it, folded the way Foundation folds them.
 *
 * The letter is Foundation's own answer from the table. What happens to the
 * marks depends on what kind of letter it is, and was measured rather than
 * guessed — every scalar there is, tried after "a", after "中", and after a
 * letter of each script:
 *
 * - a letter Foundation decomposes, meaning anything that folds to below
 *   U+0510 (Latin, Greek, Cyrillic, the fullwidth forms, the ligatures), loses
 *   every mark it knows, wherever the mark sits;
 * - a letter it leaves alone loses only the mark right after it, and only a
 *   Latin or Cyrillic combining mark;
 * - a letter it folds into something outside those scripts loses nothing.
 *
 * A Hangul syllable written as jamo is one letter. The marks that stay are
 * decomposed and put in the order of their combining classes, the spacing
 * ones first — which is where Foundation puts them.
 */
function foldCluster(cluster: string, table: Table): string {
  const first = cluster.codePointAt(0)!
  let width = first > 0xffff ? 2 : 1
  const original = cluster.slice(0, width)
  const folded = table.get(first) ?? original
  if (width === cluster.length) return folded
  let base = folded
  if (isHangul(first)) {
    while (width < cluster.length && isVowelOrTrailingJamo(cluster.charCodeAt(width))) {
      base += cluster[width]
      width += 1
    }
    if (width === cluster.length) return base
  }
  const { stripAll: all, stripFew: few, combining } = tables()
  const head = folded.codePointAt(0) ?? first
  // Folding width, the halfwidth and fullwidth block counts as folded even
  // where Foundation leaves the letter as it is (the halfwidth jamo, the
  // unassigned U+FF00). The title fold does not fold width, and there the
  // block is like any other.
  const widthBlock = table === tables().full && first >= 0xff00 && first <= 0xffef
  const kind = first === 0 ? 'none'
    : head < 0x510 ? 'all'
      : folded === original && !widthBlock ? 'first' : 'none'
  const kept: number[] = []
  for (let at = width; at < cluster.length;) {
    const scalar = cluster.codePointAt(at)!
    const size = scalar > 0xffff ? 2 : 1
    const dropped = kind === 'all'
      ? inRanges(all, scalar)
      : kind === 'first' && at === width && inRanges(few, scalar)
    if (!dropped) {
      for (const piece of String.fromCodePoint(scalar).normalize('NFD')) kept.push(piece.codePointAt(0)!)
    }
    at += size
  }
  if (kept.length === 0) return base
  // A mark with nothing before it is its own letter, and takes its place in
  // the order with the marks after it.
  const leads = width === (first > 0xffff ? 2 : 1) && (combining.get(head) ?? 0) > 0
  if (kept.length > 1 || leads) {
    // Stable: marks of one class keep the order they were written in.
    const marks = leads ? [...[...base].map((piece) => piece.codePointAt(0)!), ...kept] : kept
    const order = marks.map((scalar, index) => ({ scalar, index, rank: combining.get(scalar) ?? 0 }))
    order.sort((a, b) => a.rank - b.rank || a.index - b.index)
    return (leads ? '' : base) + String.fromCodePoint(...order.map((entry) => entry.scalar))
  }
  return base + String.fromCodePoint(kept[0])
}

/**
 * Text folded one Foundation cluster at a time: a letter — any scalar that
 * does not join the one before it, a line break included — and what joins it.
 */
function foldRun(text: string, table: Table): string {
  const { stripAll: all, full, fast, fastTitle } = tables()
  const plain = table === full ? fast : fastTitle
  let out = ''
  // Where the letter being gathered began, or -1 when there is none.
  let start = -1
  for (let at = 0; at < text.length;) {
    const unit = text.charCodeAt(at)
    const next = at + 1 < text.length ? text.charCodeAt(at + 1) : 0
    // Below U+0300 nothing joins anything: a letter of one unit, looked up.
    if (unit < 0x300 && next < 0x300) {
      if (start >= 0) out += foldCluster(text.slice(start, at), table)
      start = -1
      out += plain[unit]
      at += 1
      continue
    }
    const scalar = text.codePointAt(at)!
    if (start < 0) start = at
    else if (!joinsPrevious(scalar, all)) {
      out += foldCluster(text.slice(start, at), table)
      start = at
    }
    at += scalar > 0xffff ? 2 : 1
  }
  if (start >= 0) out += foldCluster(text.slice(start), table)
  return out
}

/** One grapheme, folded the way `String(character).folding(...)` folds it. */
function foldGrapheme(grapheme: string, table: Table): string {
  if (grapheme.length === 1) return table.get(grapheme.charCodeAt(0)) ?? grapheme
  return foldRun(grapheme, table)
}

// MARK: - Graphemes

let segmenter: Intl.Segmenter | null = null

/**
 * Where each grapheme ends, for the stretch of text that needs asking.
 *
 * Below U+0300 no character joins the one before it and none joins the one
 * after, so an English page is its own list of graphemes and costs nothing to
 * walk. Anything above that — an accent written as a mark, Korean, an emoji —
 * is handed to `Intl.Segmenter` a region at a time: from a boundary to the
 * next place two plain characters meet, which is a boundary again. Measured,
 * segmenting a page whole is fifteen times faster than asking one grapheme at
 * a time.
 */
class Graphemes {
  private ends: number[] = []
  private at = 0
  private regionEnd = -1

  constructor(private readonly text: string) {}

  /** The end of the grapheme that starts at `start`, a known boundary. */
  end(start: number): number {
    const text = this.text
    const unit = text.charCodeAt(start)
    const next = start + 1 < text.length ? text.charCodeAt(start + 1) : 0
    if (unit === 13 && next === 10) return start + 2
    if (unit < 0x300 && next < 0x300 && start >= this.regionEnd) return start + 1
    if (start >= this.regionEnd) this.segment(start)
    // Asked in order nearly always; a look ahead past a hyphen is the one
    // walk that comes back, and it starts again rather than answer wrong.
    if (this.at > 0 && this.ends[this.at - 1] > start) this.at = 0
    while (this.at < this.ends.length && this.ends[this.at] <= start) this.at += 1
    return this.ends[this.at] ?? text.length
  }

  private segment(start: number) {
    const text = this.text
    let stop = start + 1
    while (stop < text.length) {
      const before = text.charCodeAt(stop - 1)
      const here = text.charCodeAt(stop)
      if (before < 0x300 && here < 0x300 && !(before === 13 && here === 10)) break
      stop += 1
    }
    segmenter ??= new Intl.Segmenter('und', { granularity: 'grapheme' })
    this.ends = []
    const { stripAll: all } = tables()
    for (const part of segmenter.segment(text.slice(start, stop))) {
      const end = start + part.index + part.segment.length
      // A mark newer than the Unicode this engine was built with is, to it,
      // an unassigned code point and a grapheme of its own; to Swift it is a
      // mark on the letter before. Foundation's table knows it, so it goes
      // back where Swift puts it.
      const lead = part.segment.codePointAt(0)!
      const before = this.ends.length > 0 ? text.codePointAt(previousScalar(text, part.index + start)) : undefined
      if (before !== undefined && inRanges(all, lead) && UNASSIGNED.test(String.fromCodePoint(lead))
        && !CONTROL.test(String.fromCodePoint(before))) {
        this.ends[this.ends.length - 1] = end
      } else {
        this.ends.push(end)
      }
    }
    this.at = 0
    this.regionEnd = stop
  }
}

const UNASSIGNED = /^\p{Cn}$/u
/** Nothing joins a control or a line break, however new the mark is. */
const CONTROL = /^[\p{Cc}\p{Cf}\p{Zl}\p{Zp}]$/u

/** Where the scalar before `index` starts — one unit back, or two for a pair. */
function previousScalar(text: string, index: number): number {
  const low = text.charCodeAt(index - 1)
  return low >= 0xdc00 && low <= 0xdfff && index >= 2 ? index - 2 : index - 1
}

function isNewline(scalar: number): boolean {
  return (scalar >= 0x0a && scalar <= 0x0d) || scalar === 0x85 || scalar === 0x2028 || scalar === 0x2029
}

/** Unicode's White_Space, which is what `Character.isWhitespace` reads. Not
 *  JavaScript's `\s`, which also takes U+FEFF. */
function isWhitespace(scalar: number): boolean {
  if (scalar <= 0x20) return scalar === 0x20 || (scalar >= 0x09 && scalar <= 0x0d)
  if (scalar < 0x85) return false
  return scalar === 0x85 || scalar === 0xa0 || scalar === 0x1680
    || (scalar >= 0x2000 && scalar <= 0x200a) || scalar === 0x2028 || scalar === 0x2029
    || scalar === 0x202f || scalar === 0x205f || scalar === 0x3000
}

/** A hyphen the printer put there: `-`, the soft hyphen, and U+2010. */
function isBreakingHyphen(text: string, start: number, end: number): boolean {
  if (end !== start + 1) return false
  const unit = text.charCodeAt(start)
  return unit === 0x2d || unit === 0xad || unit === 0x2010
}

// MARK: - The fold

/** What `foldWithMap` hands back: the folded text, and where each unit came from. */
export interface Folded {
  text: string
  /**
   * `map[i]` is where the i-th UTF-16 unit of the folded text began in the
   * original; one more entry than the text has units, for the end — unless
   * the fold was told to stop early, in which case it ends where it stopped.
   */
  map: Int32Array
}

/** The text as it is searched, exactly as `PaperTextIndex.fold` has it. */
export function foldText(text: string): string {
  return run(text, false, Infinity).text
}

/**
 * The same fold with the way back to the original.
 *
 * `until` stops it once the folded text is longer than that many units:
 * finding where the first match of a page began only needs the fold as far
 * as the match, and folding the whole page to answer that cost as much as the
 * search itself (measured on the Mac: 47.8 ms for one query, 2.4 ms stopped).
 * Every entry up to and including `until` is the one the whole fold has.
 */
export function foldWithMap(text: string, until = Infinity): Folded {
  return run(text, true, until)
}

function run(text: string, withMap: boolean, until: number): Folded {
  const { full, fast } = tables()
  const length = text.length
  let out = new Uint16Array(length + 8)
  let map = withMap ? new Int32Array(length + 9) : new Int32Array(0)
  let size = 0
  const graphemes = new Graphemes(text)

  const room = (more: number) => {
    if (size + more < out.length) return
    const grown = new Uint16Array(Math.max(out.length * 2, size + more + 8))
    grown.set(out)
    out = grown
    if (withMap) {
      const bigger = new Int32Array(grown.length + 1)
      bigger.set(map)
      map = bigger
    }
  }
  const put = (piece: string, origin: number) => {
    room(piece.length)
    for (let unit = 0; unit < piece.length; unit += 1) {
      out[size] = piece.charCodeAt(unit)
      if (withMap) map[size] = origin
      size += 1
    }
  }

  // Whether the last thing written is the one space a run of whitespace
  // becomes. Not "the last unit is a space": Swift asks `hasSuffix(" ")` of
  // graphemes, and a space written inside another grapheme (after an Arabic
  // sign that prepends itself to what follows) is not a space to it.
  let spaced = false

  let index = 0
  while (index < length) {
    if (size > until) break
    const unit = text.charCodeAt(index)
    const next = index + 1 < length ? text.charCodeAt(index + 1) : 0

    // The common case, and nearly all of an English paper: one unit that is
    // its own grapheme.
    if (unit < 0x300 && next < 0x300 && unit !== 13) {
      if (unit === 0x2d || unit === 0xad) {
        const joined = joinsAcrossLine(text, index + 1, graphemes)
        if (joined >= 0) {
          index = joined
          continue
        }
      }
      if (isWhitespace(unit)) {
        if (size > 0 && !spaced) {
          put(' ', index)
          spaced = true
        }
        index += 1
        continue
      }
      if (unit < 0x80) {
        room(1)
        out[size] = unit >= 0x41 && unit <= 0x5a ? unit + 32 : unit
        if (withMap) map[size] = index
        size += 1
      } else {
        put(fast[unit], index)
      }
      spaced = false
      index += 1
      continue
    }

    const end = graphemes.end(index)
    const first = text.codePointAt(index)!
    if (isBreakingHyphen(text, index, end)) {
      const joined = joinsAcrossLine(text, end, graphemes)
      if (joined >= 0) {
        index = joined
        continue
      }
    }
    if (isWhitespace(first)) {
      if (size > 0 && !spaced) {
        put(' ', index)
        spaced = true
      }
      index = end
      continue
    }
    put(foldGrapheme(text.slice(index, end), full), index)
    spaced = false
    index = end
  }

  const finished = index >= length
  if (withMap && finished) map[size] = length
  return {
    text: decode(out, size),
    map: withMap ? map.slice(0, finished ? size + 1 : size) : map,
  }
}

/**
 * After a hyphen, whether the line ends before the next word: spaces and tabs,
 * then a line break. Where the text resumes if it does, or -1.
 */
function joinsAcrossLine(text: string, from: number, graphemes: Graphemes): number {
  let ahead = from
  while (ahead < text.length) {
    const unit = text.charCodeAt(ahead)
    if (unit !== 0x20 && unit !== 0x09) break
    // A space with a mark on it is a grapheme of its own, and not a space.
    const end = graphemes.end(ahead)
    if (end !== ahead + 1) break
    ahead = end
  }
  if (ahead >= text.length) return -1
  if (!isNewline(text.codePointAt(ahead)!)) return -1
  return graphemes.end(ahead)
}

const decoder = new TextDecoder('utf-16le')

function decode(units: Uint16Array, size: number): string {
  if (size === 0) return ''
  return decoder.decode(units.subarray(0, size))
}

// MARK: - Titles

/**
 * A title folded down to the form two records are compared in — the port of
 * `TextNormalization.foldedTitle`: case and accents folded (not width), then
 * only letters, marks and digits kept, every run of anything else one space.
 */
export function foldTitle(raw: string): string {
  // The whole string at once, as `String.folding` has it — not a grapheme at
  // a time, which is what the text fold does; the two part at a mark after a
  // line break.
  const { title, stripAll: all } = tables()
  const folded = foldRun(raw, title)
  let out = ''
  let lastWasSpace = true
  for (const character of folded) {
    // A mark newer than this engine's Unicode is still a mark: Foundation's
    // table knows it even where the regular expression does not.
    if (ALPHANUMERIC.test(character)
      || (UNASSIGNED.test(character) && inRanges(all, character.codePointAt(0)!))) {
      out += character
      lastWasSpace = false
    } else if (!lastWasSpace) {
      out += ' '
      lastWasSpace = true
    }
  }
  return out.trim()
}

/** `CharacterSet.alphanumerics`: letters, marks and numbers. */
const ALPHANUMERIC = /^[\p{L}\p{M}\p{N}]$/u

// MARK: - Around a match

/**
 * The words around a match, as they are set on the page — the port of
 * `PaperTextIndex.snippet(around:in:room:)`.
 */
export function snippetAround(text: string, location: number, length: number, room = 64): string {
  const start = Math.max(location - room, 0)
  const end = Math.min(location + length + room, text.length)
  let piece = text.slice(start, end).split(WHITESPACE_AND_NEWLINES).filter(Boolean).join(' ')
  // Half a word at either end reads as a typo; a leading ellipsis reads as
  // "this goes on".
  const count = () => graphemes(piece).length
  if (start > 0) {
    const space = piece.indexOf(' ')
    if (space >= 0 && count() > 12) piece = piece.slice(space + 1)
  }
  if (end < text.length) {
    const space = piece.lastIndexOf(' ')
    if (space >= 0 && count() > 12) piece = piece.slice(0, space)
  }
  return (start > 0 ? '…' : '') + piece + (end < text.length ? '…' : '')
}

/** `CharacterSet.whitespacesAndNewlines`: the Z categories, the tab, the line
 *  breaks and U+0085. */
const WHITESPACE_AND_NEWLINES = /[\p{Z}\t\n\v\f\r\x85]+/u

/** Graphemes, for the few places that count them the way Swift does. */
export function graphemes(text: string): string[] {
  const out: string[] = []
  const walker = new Graphemes(text)
  for (let index = 0; index < text.length;) {
    const end = walker.end(index)
    out.push(text.slice(index, end))
    index = end
  }
  return out
}
