#!/bin/bash
# What readers asked for, pulled back out of the issues.
#
# The issues are the one true copy: a check mark on the page is not something
# anybody remembers to tick, it is the issue being closed. This script only
# takes a photograph of that state for the two places that cannot ask GitHub
# themselves —
#
#   Website/feedback.json   the page reads the API live and falls back to this
#                           when the visitor is rate-limited or offline, the
#                           same arrangement the download counts already have.
#   App/Model/Contributors.swift
#                           the app is offline-first and asks no server, so the
#                           wall in About is baked in at release time.
#
# Run by Scripts/publish-release.sh; safe to run on its own.
set -euo pipefail

cd "$(dirname "$0")/.."

REPO="Icecoffee2500/paper-time"
LABEL="feedback"

if ! command -v gh >/dev/null 2>&1; then
  echo "feedback-sync: gh is not installed; leaving the snapshot as it is" >&2
  exit 0
fi

raw="$(mktemp)"
trap 'rm -f "$raw"' EXIT

if ! gh api -X GET "repos/$REPO/issues" \
      -f state=all -f labels="$LABEL" -f per_page=100 \
      --paginate > "$raw" 2>/dev/null; then
  echo "feedback-sync: could not read the issues; leaving the snapshot as it is" >&2
  exit 0
fi

python3 - "$raw" <<'PY'
import json, re, sys, pathlib

raw = pathlib.Path(sys.argv[1]).read_text()
# --paginate concatenates arrays; stitch them back into one.
issues = []
for chunk in re.findall(r'\[.*?\]\s*(?=\[|\Z)', raw, re.S) or [raw]:
    try:
        issues.extend(json.loads(chunk))
    except json.JSONDecodeError:
        pass
issues = [i for i in issues if isinstance(i, dict) and "pull_request" not in i]

def credit(issue):
    """The name the reporter chose, written into the body by the worker."""
    found = re.search(r"<!--\s*credit:\s*(.*?)\s*-->", issue.get("body") or "")
    if found and found.group(1).strip():
        return found.group(1).strip()
    user = (issue.get("user") or {}).get("login")
    return f"@{user}" if user else "anonymous"

rows = []
for issue in issues:
    milestone = issue.get("milestone") or {}
    rows.append({
        "number": issue.get("number"),
        "title": issue.get("title", ""),
        "state": issue.get("state", "open"),
        "html_url": issue.get("html_url", ""),
        "updated_at": issue.get("updated_at", ""),
        "milestone": {"title": milestone.get("title")} if milestone.get("title") else None,
        # Only the credit line travels, never the body: a report can hold a
        # screenshot and a person's words, and this file is committed.
        "body": f"<!-- credit: {credit(issue)} -->",
    })
rows.sort(key=lambda r: r["number"] or 0, reverse=True)

counts = {}
for issue in issues:
    who = credit(issue)
    counts[who] = counts.get(who, 0) + 1
names = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0].lower()))

pathlib.Path("Website/feedback.json").write_text(
    json.dumps({
        "issues": rows,
        "contributors": [{"name": n, "count": c} for n, c in names],
    }, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)

def swift(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

lines = "\n".join(
    f"        Contributor(name: {swift(n)}, reports: {c}),"
    for n, c in names
) or "        // Nobody yet. The first person to press ⌥⌘/ lands here."

pathlib.Path("App/Model/Contributors.swift").write_text(f'''import Foundation

/// The people who told us something, and what they are owed for it.
///
/// Generated by `Scripts/feedback-sync.sh` at release time from the issues —
/// the app asks no server for anything, so a wall that needed a network call
/// would be a wall that is usually empty. Do not edit by hand.
///
/// This is the whole of the reward, and it is the right one: somebody who
/// reported a bug opens About and finds their own name inside the app they
/// use. No points, no badges, nothing to redeem.
public struct Contributor: Sendable, Hashable, Identifiable {{
    public let name: String
    public let reports: Int
    public var id: String {{ name }}
}}

public enum Contributors {{
    public static let all: [Contributor] = [
{lines}
    ]

    public static var total: Int {{ all.reduce(0) {{ $0 + $1.reports }} }}
}}
''', encoding="utf-8")

fixed = sum(1 for i in issues if i.get("state") == "closed")
print(f"feedback-sync: {len(issues)} reports, {fixed} fixed, {len(names)} people")
PY
