# The reference tokenizer's idea of Unicode, written out for the Windows and
# Linux builds (Portable/src/shared/semantic/unicodeTables.ts).
#
# sentence-transformers reads text through Hugging Face's Rust `tokenizers`,
# and that crate classifies characters with its own tables — older than the
# JavaScript engine's in places, newer in others (its lowercasing is Rust's).
# Leaning on JavaScript's `\p{…}` and `toLowerCase()` agreed on all but 659
# code points, and *which* 659 depends on the ICU of the engine: the tests run
# on Node, the app on Electron's Chromium, and the two are different Unicode
# versions. So nothing here is left to the engine. Every code point is put to
# the reference itself — the normalizer alone on that one character, and the
# pre-tokenizer on "a<c>a" — and the answers are written down.
#
# That is exact because every step of `BertNormalizer` works a character at a
# time: dropping controls, turning spaces into ' ', padding ideographs, NFD,
# dropping nonspacing marks, lowercasing (the crate lowercases char by char,
# so a final capital sigma is σ, not ς). The one step that looks at
# neighbours is NFD's canonical reordering, and it only reorders combining
# marks — all of which but a handful of spacing ones are dropped right after.
# Hangul syllables decompose by a formula, so they are left to the formula.
#
#   HF_HOME=… HF_HUB_OFFLINE=1 python Scripts/semantic-unicode.py Portable/src/shared/semantic/unicodeTables.ts
import json, sys
import tokenizers
from transformers import AutoTokenizer

target = sys.argv[1]
tok = AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')
backend = tok.backend_tokenizer
config = json.loads(backend.to_str())
assert config['normalizer'] == {'type': 'BertNormalizer', 'clean_text': True, 'handle_chinese_chars': True,
                                'strip_accents': None, 'lowercase': True}, config['normalizer']
assert config['pre_tokenizer'] == {'type': 'BertPreTokenizer'}, config['pre_tokenizer']
norm = backend.normalizer
pre = backend.pre_tokenizer


def hangul_syllable(cp):
    return 0xAC00 <= cp <= 0xD7A3


def hangul_nfd(cp):
    s = cp - 0xAC00
    l, v, t = 0x1100 + s // 588, 0x1161 + (s % 588) // 28, 0x11A7 + s % 28
    return chr(l) + chr(v) + (chr(t) if t != 0x11A7 else '')


drop, pad, single, padded_single, multi = [], [], [], [], []
split, isolate = [], []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    c = chr(cp)
    n = norm.normalize_str(c)
    if hangul_syllable(cp):
        assert n == hangul_nfd(cp), (hex(cp), n)
    elif n == '':
        drop.append(cp)
    elif n == ' ' + c + ' ':
        pad.append(cp)
    elif n == c:
        pass
    elif len(n) == 1:
        single.append((cp, ord(n)))
    elif len(n) == 3 and n[0] == ' ' and n[2] == ' ':
        # A compatibility ideograph: padded, then NFD's canonical twin.
        padded_single.append((cp, ord(n[1])))
    else:
        multi.append((cp, n))
    pieces = [p for p, _ in pre.pre_tokenize_str('a' + c + 'a')]
    if pieces == ['a', 'a']:
        split.append(cp)
    elif pieces == ['a', c, 'a']:
        isolate.append(cp)
    else:
        assert pieces == ['a' + c + 'a'], (hex(cp), pieces)


def ranges(cps):
    """[first, last, first, last, …] over a sorted list of code points."""
    out = []
    for cp in cps:
        if out and out[-1] == cp - 1:
            out[-1] = cp
        else:
            out += [cp, cp]
    return out


def flat(pairs):
    """[from, to, from, to, …]. Runs with a common offset were tried and saved
    nothing: a letter that loses its accent moves by its own distance."""
    return [v for pair in pairs for v in pair]


def numbers(values, per_line=12):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append('  ' + ', '.join(str(v) for v in values[i:i + per_line]) + ',')
    return '\n'.join(lines)


def expanded(pairs):
    lines = []
    for cp, text in pairs:
        lines.append(f'  [{cp}, {json.dumps(text, ensure_ascii=True)}],')
    return '\n'.join(lines)


source = f'''// Generated by Scripts/semantic-unicode.py from the reference tokenizer
// (tokenizers {tokenizers.__version__}, all-MiniLM-L6-v2's tokenizer.json). Do not edit by
// hand: every number here is an answer the reference gave, and a hand edit is
// a guess. That script says why the engine's own Unicode is not used.

/** Code points `BertNormalizer` removes (controls, formats, private use, nonspacing marks…), as [first, last] pairs. */
export const DROPPED = new Uint32Array([
{numbers(ranges(drop))}
])

/** Code points it pads with spaces and otherwise keeps — its ideograph blocks — as [first, last] pairs. */
export const PADDED = new Uint32Array([
{numbers(ranges(pad))}
])

/** Code points it turns into one other code point, as [from, to] pairs in order. */
export const MAPPED = new Uint32Array([
{numbers(flat(single))}
])

/** Code points it pads with spaces and turns into one other code point (compatibility ideographs), as [from, to] pairs in order. */
export const PADDED_MAPPED = new Uint32Array([
{numbers(flat(padded_single))}
])

/** Code points it turns into several: decomposed, or a letter that lowercases to two. */
export const EXPANDED: ReadonlyArray<readonly [number, string]> = [
{expanded(multi)}
]

/** Code points `BertPreTokenizer` splits on and drops, as [first, last] pairs. */
export const SPLITS = new Uint32Array([
{numbers(ranges(split))}
])

/** Code points it cuts out into a word of their own (punctuation), as [first, last] pairs. */
export const ISOLATES = new Uint32Array([
{numbers(ranges(isolate))}
])
'''
with open(target, 'w') as f:
    f.write(source)

print(f'dropped {len(drop)} ({len(ranges(drop)) // 2} ranges), padded {len(pad)} ({len(ranges(pad)) // 2}), '
      f'mapped {len(single)}, padded+mapped {len(padded_single)}, expanded {len(multi)}, '
      f'splits {len(split)} ({len(ranges(split)) // 2}), isolates {len(isolate)} ({len(ranges(isolate)) // 2}), '
      f'{len(source.encode())} bytes')
